# This is a basic workflow to help you get started with Actions

name: Auto Minify
  # You may pin to the exact commit or the version.
  # uses: nizarmah/auto-minify@7028a7a4b79ccdc7e00f351baed61c59d07690ee
  uses: nizarmah/auto-minify@v2.1.1
  with:
    # Directory that contains the files you want to minify. Defaults to current directory (.)
    directory: # optional, default is .
    # Directory that contains the minified files. Defaults to same directory
    output: # optional, default is 
    # Overwrites the existing files with the minified version. Defaults to false.
    overwrite: # optional, default is false
    # Descend at most levels (a non-negative integer) levels of directories below the starting-points.
    maxdepth: # optional, default is 
    # Specifies which of the supported packages minifies JS files.
    js_engine: # optional, default is babel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
